name: Keep Supabase Alive

on:
  # Runs automatically at midnight every Sunday and Wednesday
  - cron: '0 0 * * 0,3'
  workflow_dispatch: # Allows you to manually trigger it for testing

jobs:
  ping_db:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase REST APIs
        env:
          URL_1: ${{ secrets.SUPABASE_URL }}
          KEY_1: ${{ secrets.SUPABASE_KEY }}
          URL_2: ${{ secrets.SUPABASE_URL_1 }}
          KEY_2: ${{ secrets.SUPABASE_KEY_1 }}
        run: |
          for i in 1 2; do
            eval SUPABASE_URL=\$URL_$i
            eval SUPABASE_KEY=\$KEY_$i

            if [ -n "$SUPABASE_URL" ]; then
              echo "----------------------------------------"
              echo "Pinging Supabase Project $i..."
              
              curl -X GET "$SUPABASE_URL/rest/v1/users?limit=1" \
              -H "apikey: $SUPABASE_KEY" \
              -H "Authorization: Bearer $SUPABASE_KEY"
              
              echo -e "\nFinished ping for project $i"
            fi
          done
